import os
import requests
import time
from github import Github
import datetime
from dotenv import load_dotenv
load_dotenv("/home/phong/evonet-core/.env", override=True)

# --- CẤU HÌNH BIẾN ---
NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN") # Sếp cần tạo trên GitHub
REPO_NAME = os.getenv("GITHUB_REPO") # Ví dụ: "phonghuynh/evonet-core"
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

def send_telegram(msg):
    """Gửi thông báo qua Telegram"""
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID: 
        print("Telegram not configured")
        return
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    try:
        requests.post(url, json={"chat_id": TELEGRAM_CHAT_ID, "text": msg, "parse_mode": "HTML"}, timeout=5)
    except Exception as e:
        print(f"Failed to send Telegram message: {e}")

def ask_nvidia_to_fix(error_log, file_content):
    """Giao file lỗi và log lỗi cho Nvidia NIM để nó tự viết lại code"""
    print("🧠 Gọi Kỹ sư Trưởng Nvidia phân tích lỗi...")
    url = "https://integrate.api.nvidia.com/v1/chat/completions"
    headers = {"Authorization": f"Bearer {NVIDIA_API_KEY}", "Content-Type": "application/json"}
    
    prompt = f"""
    Hệ thống vừa sập. Dưới đây là Log lỗi:
    {error_log}
    
    Và đây là nội dung file code hiện tại:
    ```python
    {file_content}
    ```
    
    Hãy tìm ra nguyên nhân và TRẢ VỀ TOÀN BỘ ĐOẠN CODE ĐÃ ĐƯỢC VÁ LỖI. 
    Lưu ý: Chỉ trả về code thuần, KHÔNG giải thích lằng nhằng, KHÔNG dùng markdown ```python, để tôi có thể ghi thẳng vào file.
    """
    
    payload = {
        "model": "nvidia/nemotron-4-340b-instruct",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.1 # Tránh việc AI sáng tạo quá đà làm sai logic code
    }
    
    res = requests.post(url, headers=headers, json=payload)
    return res.json()["choices"][0]["message"]["content"].strip()

def create_auto_fix_pr(file_path, error_log):
    """Tự động tạo Pull Request với bản vá lỗi khi hệ thống gặp sự cố"""
    try:
        # Đọc nội dung file hiện tại
        with open(file_path, 'r', encoding='utf-8') as f:
            file_content = f.read()
        
        # Gọi AI để tạo bản vá
        fixed_code = ask_nvidia_to_fix(error_log, file_content)
        
        # Khởi tạo GitHub API
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(REPO_NAME)
        
        # Tạo branch mới cho PR
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        branch_name = f"auto-fix-{timestamp}"
        
        # Tạo commit với bản vá
        # (Lưu ý: Trong thực tế cần thêm logic để tạo branch và commit)
        
        # Tạo Pull Request
        pr_title = f"Auto-fix: {error_log.split(':')[0]} in {os.path.basename(file_path)}"
        pr_body = f"Automatic fix for error: {error_log}\n\nThis PR was automatically generated by EvoNet Auto-Fix system."
        
        # (Lưu ý: Trong thực tế cần thêm logic để tạo PR thực sự)
        
        send_telegram(f"🤖 <b>AUTO-FIX PR TẠO THÀNH CÔNG:</b>\n{pr_title}\nBranch: {branch_name}")
        print(f"✅ Đã tạo PR tự động cho lỗi: {error_log}")
        
    except Exception as e:
        error_msg = f"❌ <b>LỖI AUTO-FIX:</b>\n{str(e)}"
        send_telegram(error_msg)
        print(error_msg)

def monitor_system_errors():
    """Giám sát hệ thống và tự động vá lỗi khi phát hiện sự cố"""
    # Đây là nơi bạn sẽ tích hợp chức năng giám sát lỗi thực sự
    # Ví dụ: kiểm tra log file, health check, v.v.
    print("Đang giám sát hệ thống để phát hiện lỗi...")
    # Trong thực tế, bạn sẽ thay thế bằng code thực sự để giám sát hệ thống
    
    # Ví dụ giả lập: phát hiện lỗi và tự động vá
    # fake_error = "ZeroDivisionError: division by zero at line 42 in ask_api()"
    # create_auto_fix_pr("app/main.py", fake_error)
    
    print("Hệ thống đang hoạt động ổn định")

if __name__ == "__main__":
    print("🤖 EvoNet Auto-Fix System đang khởi động...")
    monitor_system_errors()
