import os
import requests
from github import Github
import datetime
from dotenv import load_dotenv

load_dotenv("/app/.env", override=True)

NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO_NAME = os.getenv("GITHUB_REPO")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")


def send_telegram(msg):
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        return
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    try:
        requests.post(url, json={"chat_id": TELEGRAM_CHAT_ID, "text": msg, "parse_mode": "HTML"}, timeout=5)
    except Exception as e:
        print(f"Telegram error: {e}")


def ask_nvidia_to_fix(error_log, file_content):
    url = "https://integrate.api.nvidia.com/v1/chat/completions"
    headers = {"Authorization": f"Bearer {NVIDIA_API_KEY}", "Content-Type": "application/json"}
    prompt = f"""System crashed. Error log:
{error_log}

Current file content:
```python
{file_content}
```

Fix the bug and return ONLY the fixed code. No markdown, no explanation."""
    payload = {
        "model": "nvidia/qwen2.5-coder-32b-instruct",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.1,
        "max_tokens": 4096
    }
    res = requests.post(url, headers=headers, json=payload, timeout=180)
    res.raise_for_status()
    return res.json()["choices"][0]["message"]["content"].strip()


def create_auto_fix_pr(file_path, error_log):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            file_content = f.read()

        fixed_code = ask_nvidia_to_fix(error_log, file_content)

        # Save as draft for HITL approval
        draft_path = os.path.join(os.path.dirname(file_path), "main_draft.py")
        with open(draft_path, 'w', encoding='utf-8') as f:
            f.write(fixed_code)

        # Create GitHub PR if credentials available
        if GITHUB_TOKEN and REPO_NAME:
            try:
                g = Github(GITHUB_TOKEN)
                repo = g.get_repo(REPO_NAME)
                timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                branch_name = f"auto-fix-{timestamp}"

                # Get default branch
                default_branch = repo.get_branch(repo.default_branch)
                repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=default_branch.commit.sha)

                # Update file on the new branch
                contents = repo.get_contents(file_path, ref=branch_name)
                repo.update_file(
                    file_path,
                    f"Auto-fix: {error_log[:50]}",
                    fixed_code,
                    contents.sha,
                    branch=branch_name
                )

                # Create PR
                pr = repo.create_pull(
                    title=f"Auto-fix: {os.path.basename(file_path)}",
                    body=f"Automatic fix for:\n```\n{error_log}\n```\n\nGenerated by EvoNet Auto-Fix.",
                    head=branch_name,
                    base=repo.default_branch
                )
                send_telegram(f"🤖 <b>AUTO-FIX PR CREATED:</b>\n{pr.title}\n{pr.html_url}")
                return
            except Exception as e:
                print(f"GitHub PR error: {e}")

        send_telegram(f"🤖 <b>AUTO-FIX DRAFT READY:</b>\nSaved to {draft_path}\nUse /duyet_tienhoa to approve")
        print(f"Auto-fix draft saved to {draft_path}")

    except Exception as e:
        send_telegram(f"❌ <b>AUTO-FIX ERROR:</b>\n{str(e)}")
        print(f"Auto-fix error: {e}")


def monitor_system_errors():
    error_log_path = "logs/error.log"
    if os.path.exists(error_log_path) and os.path.getsize(error_log_path) > 0:
        with open(error_log_path, 'r') as f:
            error_log = f.read()
        if error_log.strip():
            create_auto_fix_pr("app/main.py", error_log)
            # Clear the error log after processing
            open(error_log_path, 'w').close()
    else:
        print("System operating normally")


if __name__ == "__main__":
    print("EvoNet Auto-Fix System starting...")
    monitor_system_errors()
